# Generated by Django 4.2.4 on 2023-09-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
